---
author: Hal Svien
date: "07/12/2020"
output: 
  bookdown::pdf_document2:
    toc: false
---

Curriculum Vitae

Harold Svien

July 2020

Contact Information
14913 S. Ox Cart Ln.

Draper, UT, 84043

(760) 803-1388

halsvien@gmail.com

Education
2015 Bachelor of Science, Criminology & Criminal Justice, minor in Psychology

California State University, Long Beach

2019 Master of Science, Clinical Psychology

Brigham Young University

2021 Graduate Professional Certificate, Data Science

Harvard University

Selected Employment History
04/2020 – Present Product Analyst

Finicity

Murray, UT

Supervisor: Ryan Christiansen, SVP

Create product business and functional requirements for new products
Manage story creation in JIRA
Manage projects and initiatives important to product roadmap
Assist with the creation of product documentation
Analyze data sets to assist in data quality efforts
09/2017 – 11/2019 Research Assistant

Brigham Young University

Provo, UT

Supervisor: Gary M. Burlingame, PhD

Provide support as needed in multiple studies and research projects (e.g., meta-analyses, systematic reviews, randomized controlled trials, research reviews)
Prepare research materials and results for publication and dissemination
Administer various demographic and psychometric measures to participants in research studies
Coding and sorting data for analysis
Researching, writing, and preparing for various presentations at professional conferences including SPR, AGPA, and APA
Assisting in writing research grant proposals
Research Experience
08/2014 – 05/2015 Research Assistant

Frontal Lobe Function, Crime, Psychopathology, Neuropsychology and Brain Injury

California State University, Long Beach

Supervisor: Robert A. Schug, PhD

Preparing and recording electroencephalogram usingBIOPAC AcqKnowledge software; cleaning and maintaining electroencephalogram equipment
Administering and scoring of various neuropsychology tests including: RAVLT, WAIS IV, Wechsler Memory Scale, Trailmaking Test, Wisconsin Card Sorting Test, Grooved Pegboard, Tower of London, Iowa Gambling Task
Administering of other questionnaires including: Traumatic Brain Injury Screening, Schizotypal Personality Questionnaire, Self-Report Crime Questionnaire, Displaced Aggression Questionnaire, MCMI-III, SCL-II
Inputting and analyzing various data using SPSS software
Creating a Go/No-go task using SuperLab software
Training and supervising research assistants
Managing of day to day laboratory needs
Researching, writing, and preparing for various presentations at professional conferences including SPSP, WPA, and WSC
Assisting in writing research proposals
Conducting experiments sessions and participant interactions including: greeting participants during initial stage of experiment, explaining the study and informed consent, debriefing, and contacting participants about follow-up studies
01/2015 – 05/2015 Research Assistant

The Impact of Collective Rumination on Aggressive Behavior

California State University, Long Beach

Supervisor: William C. Pedersen, Ph.D.

Conducting experiment sessions and participant interactions including: greeting participants during initial stage of experiments, explaining the study and informed consent, running experiment, and debriefing
09/2017 – Present Research Assistant

Compassion Focused Group Therapy in College Counseling Center Populations: A Feasibility Trial

Brigham Young University

Supervisor: Gary M. Burlingame, PhD

Supervise administration of study materials to participants
Edit and create psychotherapy manual for use in research and practice
Administer psychometric and biometric measures involving study participants
Prepare preliminary and final results for publication and/or presentation
Awards and Scholarships
California State University, Long Beach President's List, Fall 2014

(Awarded to students with a semester grade point average of 3.750 or greater)

California State University, Long Beach President's List, Spring 2015

(Awarded to students with a semester grade point average of 3.750 or greater)

Recipient of Garner Family Scholarship in the College of Family, Home, and Social Sciences at Brigham Young University

Recipient of an Experiential Learning Fund grant in the College of Family, Home, and Social Sciences at Brigham Young University (July 2019)

Recipient of an Experiential Learning Fund grant in the College of Family, Home, and Social Sciences at Brigham Young University (October 2019)

Academic and Professional Memberships
Member of Psi Chi, The International Honor Society in Psychology

Member of the Golden Key International Honor Society

Member of the American Group Psychotherapy Association

Member of the Society for Psychotherapy Research

Member of the Western Psychological Association

Professional Presentations
*Indicates a project which I supervised

* Clement, Z., Nicoll, J., Svien, H. , & Burlingame, G. M. (2020). Cognitive-behavioral group therapy for psychosis: A follow-up meta-analysis and synthesis. Presented at the 2020 Annual American Group Psychotherapy Association meeting (AGPA Connect 2020), March 2-7, 2020; New York, NY.

Svien, H. , Rivera, I. (2019). Group facilitation training in early career professionals: 2020 AGPA survey results. Presented at the 2020 Annual American Group Psychotherapy Association meeting (AGPA Connect 2020), March 2-7, 2020; New York, NY.

*Washburn, A., Peery, A., Svien, H. , Alldredge, C., & Burlingame, G. M. (2020). Measures of shame in psychology: A systematic review. Presented at the 14th Annual Utah Conference for Undergraduate Research (UCUR 2020), February 7, 2020; Logan, Utah.

*Nicoll, J., Clement, Z., Svien, H. , & Burlingame, G. M. (2020). Cognitive-behavioral group therapy for psychosis: A follow-up meta-analysis. Presented at the 14th Annual Utah Conference for Undergraduate Research (UCUR 2020), February 7, 2020; Logan, Utah.

Lambert, M. J. (2019). Workshop: Construction of scientific evidence in clinical research. Part of an invited contingent of contributors from the United States. Presented at the 1st Annual São Paulo School of Advanced Science in Mental Health and Evidence-based Interventions (ESPCA [Portuguese to English translation]), October 1-10, 2019; Amparo, São Paulo, Brazil.

Burlingame, G. M., & Svien, H. (2019). Group psychotherapy & value-based payment: Balancing the way with data from daily mental health practice. Presented as the Division 49 President's keynote address at the 2019 meeting of the American Psychological Association (APA 2019), August 8-11, 2019; Chicago, Illinois.

Burlingame, G. M., Janis, R. A., & Svien, H. (2019). Group therapy for mood disorders: Results of a meta-analysis. Presented at the 2019 international Society for Psychotherapy Research meeting (SPR 2019), July 3-6, 2019; Buenos Aires, Argentina.

Svien, H. , Burlingame, G. M., & Rosendahl, J. (2019). Group therapy for schizophrenia: Results of a meta-analysis. Presented at the 2019 international Society for Psychotherapy Research meeting (SPR 2019), July 3-6, 2019; Buenos Aires, Argentina.

*Svien, H. , Cattani, K., Jensen, J., Chun, S., & Burlingame, G. M. (2019). Moderators of compassion-focused group therapy for college students. Presented at the 2019 Annual American Group Psychotherapy Association meeting (AGPA Connect 2019), February 25-March 2, 2019; Los Angeles, California.

Jensen, J., Burlingame, G. M., Cattani, K., & Svien, H. (2018). Compassioned focused group therapy in college counseling center populations: A feasibility trial. Presented at the 2018 annual North American chapter of the Society for Psychotherapy Research meeting (NASPR 2018), September 27-29, 2018; Snowbird, Utah.

Svien, H. , Burlingame, G. M., & Olsen, J. A. (2018). Describing therapeutic relationship change and failure in group psychotherapy. Presented at the 2018 international Society for Psychotherapy Research meeting (SPR 2018), June 27-30, 2018; Amsterdam, The Netherlands.

Svien, H. , Alldredge, C., Jensen, J., & Burlingame, G. M. (2018). Compassion focused group therapy in college counseling center populations: A feasibility trial. Presented at the 2018 Annual American Group Psychotherapy Association meeting (AGPA Connect 2018), February 26-March 3, 2018; Houston, Texas.

Ellison, J. M., Pedersen, W. C., Flores, R., Geraci, G. G., Hardin, K., Harris, K., Henley, P., LeBlanc, S., Lopez, C., Madsen, E., Svien, H. , Tababa, D. R., Taylor, A., & Zamorano, C. (2017). The moderating effect of intergroup versus interpersonal context on the relationship between collective rumination and aggression. Presented at the 18th Annual Society for Personality and Social Psychology Conference (SPSP 2017), July 5-19, 2017; San Antonio, Texas.

Svien, H. , Javaheri, P., McLernon, H., Geraci, G. G., Kim, E., Marin, B., Partida, L., Paul, H., Pedersen, W. C., Ostergren, J., & Schug, R. A. (2015). Illegal drug crime and trait displaced aggression. Poster presented at the 95th annual convention of the Western Psychological Association (WPA 2018), April 30-May 3; Las Vegas, Nevada.

Publications
Svien, H. , Burlingame, G. M., & Dooley-Feldman, E. (under preparation). Ruptures in group psychotherapy: Conceptual and empirical considerations.

Svien, H. , Burlingame, G. M., Griner, D., & Beecher, M. (under preparation). Describing therapeutic relationship change and failure in group psychotherapy.

Janis, R. A., Burlingame, G. M., & Svien, H. (under preparation). Group therapy for mood disorders: A meta-analysis.

Burlingame, G. M., Svien, H. , Hoppe, L., Hunt, I. & Rosendahl, J. (under review). Group therapy for schizophrenia: A meta-analysis.

Svien, H. , Janis., R. A., & Burlingame, G. M. (2019). Progress feedback in group therapy: The past and the future [web-only feature]. Retrieved from https://bit.ly/2MHKTLJ

Svien, H. , & Burlingame, G. M. (2019). Trends in modern group psychotherapy for schizophrenia. International Journal of Group Psychotherapy, 69, 347-352. doi:https://doi.org/10.1080/00207284.2019.1584528

Burlingame, G. M., Gleave, R. L., Beecher, M. E., Griner, D., Hansen, K. S. W., Jensen, J., Worthen, V., & Svien, H. (2017). Administration and scoring manual for the Group Questionnaire-GQ. Salt Lake City, UT: OQ Measures L.L.C.

Peer Review Experiences
Ad Hoc Reviewing (Journal/Organization)
Clinical Psychology & Psychotherapy

Psychological Services

Psychotherapy Research

Stroke Association (UK)

Clinical Experiences
09/2017 – Present Practicum Student

The Comprehensive Clinic at Brigham Young University

Provo, UT

Supervisors (all PhDs): Mikle South, Kat Green, Chad Jensen, Melissa Jones

Conduct integrative psychological assessments using evidence-based measures based on client presenting concern(s)
Total integrated assessment reports: 10
Conduct evidence-based practice in psychotherapy based on presenting client concerns
Major concerns seen: generalized anxiety disorder, depression (dysthymia and major depressive disorders), mood inconsistency (i.e., depressive and hypomanic states), personality concerns (e.g., borderline characteristics), sexual assault, eating disorder symptoms, obsessive-compulsive symptoms
Theoretical orientations: cognitive-behavioral therapy (CBT; including behavioral activation), dialectical behavior therapy (DBT), and interpersonal psychotherapy (IPT)
05/2019 – Present Practicum Extern

Psychological Assessment and Intervention Resources (PAIR)

South Jordan, UT

Supervisor: Thad Q. Lloyd, PhD

Conduct comprehensive dialectical behavior therapy (DBT) with outpatient clients
Lead and co-lead DBT skills group with adult outpatient clients
Conduct individual DBT psychotherapy
Give as-needed phone coaching to outpatient clients
Attend weekly DBT consultation group
Conduct personality assessments as-needed to determine diagnostic specificity with potential clients and suitability for comprehensive DBT
05/2019 – Present Practicum Extern

Salt Lake City Veterans Health Administration

Salt Lake City, UT

Supervisor: Kevin Laska, PhD

Conduct evidence-based psychotherapy with US Armed Forces veterans presenting with diverse concerns
Major concerns seen: posttraumatic stress disorder, obsessive-compulsive disorder, martial discord, intermittent explosive disorder, schizophrenia
Theoretical orientations: cognitive behavioral therapy (CBT; including behavioral activation) and interpersonal psychotherapy (IPT)
Service Experiences
Committee Membership
American Group Psychotherapy Association E-Learning Taskforce

Relevant Technology Experience
Git version control software

GitHub

Jupyter Notebooks

Microsoft Office

MySQL

Python 3

Qualtrics online survey software

Q Interactive online assessment software

Q Global online assessment software

R statistics software

RStudio IDE

SPSS statistics software

Stata statistics software

Tableau Desktop

Teradata